### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by Gitwithsuman** [Kuwarsaab/git-learn#34]
hi kuwarsaab, thanks for accepting all my request but i want to add more so in sorting folder i want to add Counting and  Counting Sort works by counting occurrences of each unique element in the array and O(n + k) where n is the number of elements in the input array, and k is the range of the input and please assign me this and give please **hactoberfest** tag. really thanks for helping me.

**Comment by Vishrut99** [comment]
can you please assign me ?
