### ISSUE TITLE
Issue: Shortest Path in Unweighted Graph (BFS in C++)

### ISSUE THREAD

**Issue by Nikhil-gi** [Kuwarsaab/git-learn#38]
Hello @Kuwarsaab ,

I would like to work on the "Shortest Path in Unweighted Graph" problem under Hacktoberfest and Hacktoberfest2024. Could you please assign this issue to me?

I will implement the Breadth-First Search (BFS) algorithm in C++, ensuring clarity, performance, and proper test coverage. Looking forward to your confirmation!

Thanks,
Nikhil

**Comment by Kuwarsaab** [comment]
The task assigned to you!
