### ISSUE TITLE
Creating a stopwatch

### ISSUE THREAD

**Issue by himanshidayal14** [Kuwarsaab/git-learn#47]
Please assign me this project.

**Comment by Kuwarsaab** [comment]
Please add the task is assigned to you!

**Comment by Smriti-Prajapati** [comment]
Hey please assign this issue to me for Hactoberfest 2024.

**Comment by supraik** [comment]
hey please assign me this project

**Comment by himanshidayal14** [comment]
@Kuwarsaab Yes sir, I am working on the task assigned to me. I will complete it by 12 PM.
