### ISSUE TITLE
Can i add portfolio for students

### ISSUE THREAD

**Issue by Kedarnath-Rothe** [Kuwarsaab/git-learn#5]
Please assign me

**Comment by Kuwarsaab** [comment]
Hello Kedarnath,
You can add portfolio for students!

**Comment by Kedarnath-Rothe** [comment]
@Kuwarsaab, I have added Portfolio for students.. Please check and accept and merge my PR
![Screenshot 2024-10-06 193520](https://github.com/user-attachments/assets/c261f0f9-ecbb-47c0-a46e-37a969547083)
