### ISSUE TITLE
External Link Takes Users Away from the Website 

### ISSUE THREAD

**Issue by Ishita-Trivedi** [Kuwarsaab/git-learn#84]
There is an issue where a specific link on our website navigates the user to an external site without opening a new tab. This behavior is not ideal because it takes users away from our platform, potentially affecting user engagement and the overall experience. @Kuwarsaab 
Please assign me the issue to work on it?

**Comment by Kuwarsaab** [comment]
Assigned the #84 to you @Ishita-Trivedi
